let words = [
   { wordgreek: "ελληνικά", wordenglish: "Greek", wordclass: "noun" },
   { wordgreek: "αγάπη", wordenglish: "love", wordclass: "noun" },
   { wordgreek: "παλτό", wordenglish: "coat", wordclass: "noun" },
   { wordgreek: "παντελόνι", wordenglish: "pants", wordclass: "noun" },
   { wordgreek: "άντρας", wordenglish: "man", wordclass: "noun" },
   { wordgreek: "γυναίκα", wordenglish: "woman", wordclass: "noun" },
   { wordgreek: "σπίτι", wordenglish: "house", wordclass: "noun" },
   { wordgreek: "βιβλίο", wordenglish: "book", wordclass: "noun" },
   { wordgreek: "θάλασσα", wordenglish: "sea", wordclass: "noun" },
   { wordgreek: "παραλία", wordenglish: "beach", wordclass: "noun" },
   { wordgreek: "παράθυρο", wordenglish: "window", wordclass: "noun" },
   { wordgreek: "παιδί", wordenglish: "child", wordclass: "noun" },
   { wordgreek: "δάσος", wordenglish: "forest", wordclass: "noun" },
   { wordgreek: "λεωφορείο", wordenglish: "bus", wordclass: "noun" },
   // Глаголы
   { wordgreek: "τρέχω", wordenglish: "run", wordclass: "verb" },
   { wordgreek: "γράφω", wordenglish: "write", wordclass: "verb" },
   { wordgreek: "διαβάζω", wordenglish: "read", wordclass: "verb" },
   { wordgreek: "πηγαίνω", wordenglish: "go", wordclass: "verb" },
   { wordgreek: "τρώω", wordenglish: "eat", wordclass: "verb" },
   { wordgreek: "πίνω", wordenglish: "drink", wordclass: "verb" },
   { wordgreek: "μιλάω", wordenglish: "speak", wordclass: "verb" },
   { wordgreek: "ακούω", wordenglish: "hear", wordclass: "verb" },
   { wordgreek: "δουλεύω", wordenglish: "work", wordclass: "verb" },
   { wordgreek: "αγοράζω", wordenglish: "buy", wordclass: "verb" },
   // Прилагательные в мужском роде
   { wordgreek: "μεγάλος", wordenglish: "big", wordclass: "adjective" },
   { wordgreek: "μικρός", wordenglish: "small", wordclass: "adjective" },
   { wordgreek: "όμορφος", wordenglish: "beautiful", wordclass: "adjective" },
   { wordgreek: "ψηλός", wordenglish: "tall", wordclass: "adjective" },
   { wordgreek: "χαρούμενος", wordenglish: "happy", wordclass: "adjective" },
   { wordgreek: "γρήγορος", wordenglish: "fast", wordclass: "adjective" },
   { wordgreek: "αργός", wordenglish: "slow", wordclass: "adjective" },
   { wordgreek: "δυνατός", wordenglish: "strong", wordclass: "adjective" },
   { wordgreek: "έξυπνος", wordenglish: "smart", wordclass: "adjective" },
   { wordgreek: "ήσυχος", wordenglish: "quiet", wordclass: "adjective" },
   // Наречия
   { wordgreek: "γρήγορα", wordenglish: "quickly", wordclass: "adverb" },
   { wordgreek: "αργά", wordenglish: "slowly", wordclass: "adverb" },
   { wordgreek: "σήμερα", wordenglish: "today", wordclass: "adverb" },
   { wordgreek: "χθες", wordenglish: "yesterday", wordclass: "adverb" },
   { wordgreek: "πολύ", wordenglish: "very", wordclass: "adverb" },
   { wordgreek: "λίγο", wordenglish: "a little", wordclass: "adverb" },
   { wordgreek: "πάντα", wordenglish: "always", wordclass: "adverb" },
   { wordgreek: "ποτέ", wordenglish: "never", wordclass: "adverb" },
   { wordgreek: "εκεί", wordenglish: "there", wordclass: "adverb" },
   { wordgreek: "εδώ", wordenglish: "here", wordclass: "adverb" },
];

export default words;